<?php

/**
 * Plugin Name:       LSX Label/Value Group
 * Description:       Group-like block that aligns/wraps .value relative to .label with adjustable label width and padding.
 * Version:           0.1.0
 * Author:            LightSpeed
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       lsx-label-value-group
 *
 * @package           lsx-label-value-group
 */

if (! defined('ABSPATH')) {
    exit;
}

add_action('init', function () {
    // Registers assets & block from build/block.json (generated by wp-scripts).
    register_block_type(__DIR__ . '/build');
});
